#! /bin/sh
#
# Set up environment variables for thames, and run it
#
ISIS=../ISIS-II

ISIS_F0=.
ISIS_F1=${ISIS}/PLM80
ISIS_F2=${ISIS}/ASM80
ISIS_F3=${ISIS}/UTILS

export ISIS_F0 ISIS_F1 ISIS_F2 ISIS_F3

./thames $*
